# Generated by scripts/update-sources. Do not edit by hand.
{
  "aws" = {
    "x86_64-linux" = {
      version = "2.2.0";
      imageName = "floci/floci";
      upstreamTag = "2.2.0";
      imageDigest = "sha256:e97cd0c1dc2aa14e7697fb5ef5018404c4d6345169dbd276315f0bed2c7b0520";
      hash = "sha256-GnsGBp30/TMW7ykYE4CKW/CCUhmqaPfi1rydnSn4jRY=";
      finalImageName = "floci-nix/aws";
      finalImageTag = "2.2.0-sha256-e97cd0c1dc2aa14e";
      arch = "amd64";
    };
    "aarch64-linux" = {
      version = "2.2.0";
      imageName = "floci/floci";
      upstreamTag = "2.2.0";
      imageDigest = "sha256:e97cd0c1dc2aa14e7697fb5ef5018404c4d6345169dbd276315f0bed2c7b0520";
      hash = "sha256-kaLZw6Ajk+dAiSurHudHaPNgD1vcckTzFy+iBZ7YQBQ=";
      finalImageName = "floci-nix/aws";
      finalImageTag = "2.2.0-sha256-e97cd0c1dc2aa14e";
      arch = "arm64";
    };
  };

  "aws-compat" = {
    "x86_64-linux" = {
      version = "2.2.0";
      imageName = "floci/floci";
      upstreamTag = "2.2.0-compat";
      imageDigest = "sha256:8576f87f9b5004c74685b8743712a981f352d53e9c227daeba6d341d09aba4c7";
      hash = "sha256-i6KQuSIrUNeNV0hnl2mSQM95lbQ5iqpXi485g2Zfkuo=";
      finalImageName = "floci-nix/aws-compat";
      finalImageTag = "2.2.0-sha256-8576f87f9b5004c7";
      arch = "amd64";
    };
    "aarch64-linux" = {
      version = "2.2.0";
      imageName = "floci/floci";
      upstreamTag = "2.2.0-compat";
      imageDigest = "sha256:8576f87f9b5004c74685b8743712a981f352d53e9c227daeba6d341d09aba4c7";
      hash = "sha256-RO4SXB5RH9llYRzH/m9zR1tTBS7pYQo5TEuTncDvJ/M=";
      finalImageName = "floci-nix/aws-compat";
      finalImageTag = "2.2.0-sha256-8576f87f9b5004c7";
      arch = "arm64";
    };
  };

  "aws-baseline" = {
    "aarch64-linux" = {
      version = "2.2.0";
      imageName = "floci/floci";
      upstreamTag = "2.2.0-baseline";
      imageDigest = "sha256:1ddc8cbbaf290bb88cd10dad302a730ce6730d42f227cf18b84a9f1f372615f6";
      hash = "sha256-obzqrDfZfB6rWoBDKK/kQ6fsn5p8M46GAEOe5QKWwcY=";
      finalImageName = "floci-nix/aws-baseline";
      finalImageTag = "2.2.0-sha256-1ddc8cbbaf290bb8";
      arch = "arm64";
    };
  };

  "azure" = {
    "x86_64-linux" = {
      version = "0.14.0";
      imageName = "floci/floci-az";
      upstreamTag = "0.14.0";
      imageDigest = "sha256:a35e74dfca9a5e811090d8ae98876044fc8990a8874ee525231f524ca56679db";
      hash = "sha256-ObURv9ZnmFknV/tcAf3OFmiPVoLEZ7Rr+Lk67q4G9zU=";
      finalImageName = "floci-nix/azure";
      finalImageTag = "0.14.0-sha256-a35e74dfca9a5e81";
      arch = "amd64";
    };
    "aarch64-linux" = {
      version = "0.14.0";
      imageName = "floci/floci-az";
      upstreamTag = "0.14.0";
      imageDigest = "sha256:a35e74dfca9a5e811090d8ae98876044fc8990a8874ee525231f524ca56679db";
      hash = "sha256-VbYD/FCYMqJbQiSoElLCVbNmJ93oOxfWErREk4JjLXQ=";
      finalImageName = "floci-nix/azure";
      finalImageTag = "0.14.0-sha256-a35e74dfca9a5e81";
      arch = "arm64";
    };
  };

  "gcp" = {
    "x86_64-linux" = {
      version = "0.10.0";
      imageName = "floci/floci-gcp";
      upstreamTag = "0.10.0";
      imageDigest = "sha256:405c128b685afbc461276820f2286defcc3a6fa478755067d3e3f740c5503c07";
      hash = "sha256-9ZhHBqR8HZRkB5OX5fxrw+FAPdFUrCSJ0kJ+XAz1SkI=";
      finalImageName = "floci-nix/gcp";
      finalImageTag = "0.10.0-sha256-405c128b685afbc4";
      arch = "amd64";
    };
    "aarch64-linux" = {
      version = "0.10.0";
      imageName = "floci/floci-gcp";
      upstreamTag = "0.10.0";
      imageDigest = "sha256:405c128b685afbc461276820f2286defcc3a6fa478755067d3e3f740c5503c07";
      hash = "sha256-d+EC6C5MeunP4BuSrAAQTu6jdBkW95hJgusGqG55f/8=";
      finalImageName = "floci-nix/gcp";
      finalImageTag = "0.10.0-sha256-405c128b685afbc4";
      arch = "arm64";
    };
  };

  "oci" = {
    "x86_64-linux" = {
      version = "0.4.2";
      imageName = "floci/floci-oci";
      upstreamTag = "0.4.2";
      imageDigest = "sha256:98ba24585a582ed0b1f482aa4ac11fcd65f39effec51c3ada8a3182b30bcad3b";
      hash = "sha256-fumc47F9FpN/19rP/KPntgN/Wjn0Z+CyJ+Pfxv50H3Q=";
      finalImageName = "floci-nix/oci";
      finalImageTag = "0.4.2-sha256-98ba24585a582ed0";
      arch = "amd64";
    };
    "aarch64-linux" = {
      version = "0.4.2";
      imageName = "floci/floci-oci";
      upstreamTag = "0.4.2";
      imageDigest = "sha256:98ba24585a582ed0b1f482aa4ac11fcd65f39effec51c3ada8a3182b30bcad3b";
      hash = "sha256-GkdQ1BRD8PaENfkEzt+oH58wBjE+XQI56Puum7fFTw4=";
      finalImageName = "floci-nix/oci";
      finalImageTag = "0.4.2-sha256-98ba24585a582ed0";
      arch = "arm64";
    };
  };

  "oci-compat" = {
    "x86_64-linux" = {
      version = "0.4.2";
      imageName = "floci/floci-oci";
      upstreamTag = "0.4.2-compat";
      imageDigest = "sha256:1a200fae5aaa90f611f9892c24db9f07465fcfc66be4ea169738d7be20bb8af1";
      hash = "sha256-jLIKn0TkdmZPcZuj9vHXGYb02mqkMv/6dIWVnp0QOuw=";
      finalImageName = "floci-nix/oci-compat";
      finalImageTag = "0.4.2-sha256-1a200fae5aaa90f6";
      arch = "amd64";
    };
    "aarch64-linux" = {
      version = "0.4.2";
      imageName = "floci/floci-oci";
      upstreamTag = "0.4.2-compat";
      imageDigest = "sha256:1a200fae5aaa90f611f9892c24db9f07465fcfc66be4ea169738d7be20bb8af1";
      hash = "sha256-/XS1wUm1C3g0NtgSmY9oKtOLGqWRrP3EH4YobJ4oicI=";
      finalImageName = "floci-nix/oci-compat";
      finalImageTag = "0.4.2-sha256-1a200fae5aaa90f6";
      arch = "arm64";
    };
  };
}
