# Generated by scripts/update-sources. Do not edit by hand.
{
  version = "0.3.0";
  tag = "0.3.0";
  url = "https://github.com/floci-io/floci-cli/releases/download/0.3.0/floci.jar";
  hash = "sha256-/8L4ddcgEV6GBfPil7jeyld9eC+MOtJJsLGtPHGIm9k=";
}
