# Generated by scripts/update-sources. Do not edit by hand.
{
  version = "0.2.3";
  tag = "0.2.3";
  url = "https://github.com/floci-io/floci-cli/releases/download/0.2.3/floci.jar";
  hash = "sha256-Dcpc0Xf1Z0F2BbtGhhmHbbg1ljbwStE5L/rtYoaOP0M=";
}
