# Generated by scripts/update-sources. Do not edit by hand.
{
  "aws" = {
    "x86_64-linux" = {
      version = "2.1.0";
      imageName = "floci/floci";
      upstreamTag = "2.1.0";
      imageDigest = "sha256:f5aa8c18302cedb4f2385f5c4e455b3efc77fee6bf7b6e5d1712b2817ba102db";
      hash = "sha256-nlPmZx0guN2SuphQ8I12aE7LclqWvzUFKWsd9Ig8zIo=";
      finalImageName = "floci-nix/aws";
      finalImageTag = "2.1.0-sha256-f5aa8c18302cedb4";
      arch = "amd64";
    };
    "aarch64-linux" = {
      version = "2.1.0";
      imageName = "floci/floci";
      upstreamTag = "2.1.0";
      imageDigest = "sha256:f5aa8c18302cedb4f2385f5c4e455b3efc77fee6bf7b6e5d1712b2817ba102db";
      hash = "sha256-obB013g2Ut1w1ToE8LPmYv44cTkvIzQ1t8j0AHiyYPA=";
      finalImageName = "floci-nix/aws";
      finalImageTag = "2.1.0-sha256-f5aa8c18302cedb4";
      arch = "arm64";
    };
  };

  "aws-compat" = {
    "x86_64-linux" = {
      version = "2.1.0";
      imageName = "floci/floci";
      upstreamTag = "2.1.0-compat";
      imageDigest = "sha256:bb98b11f837bdacdda21ce6635a0773509e50aa471c35be9332a9efef502127c";
      hash = "sha256-TjYu/LCjnpQq0FKEcSbi6fx9HVmPA8DBEwCXik9MWb0=";
      finalImageName = "floci-nix/aws-compat";
      finalImageTag = "2.1.0-sha256-bb98b11f837bdacd";
      arch = "amd64";
    };
    "aarch64-linux" = {
      version = "2.1.0";
      imageName = "floci/floci";
      upstreamTag = "2.1.0-compat";
      imageDigest = "sha256:bb98b11f837bdacdda21ce6635a0773509e50aa471c35be9332a9efef502127c";
      hash = "sha256-RGe/25tNL3A3YHwpwNWDvODZkDQDr/MT3F7o4YFxKfE=";
      finalImageName = "floci-nix/aws-compat";
      finalImageTag = "2.1.0-sha256-bb98b11f837bdacd";
      arch = "arm64";
    };
  };

  "aws-baseline" = {
    "aarch64-linux" = {
      version = "2.1.0";
      imageName = "floci/floci";
      upstreamTag = "2.1.0-baseline";
      imageDigest = "sha256:5e8d00757d225bdcb80e7481ebb7bcc623afcdbe842097a133b8d218e65a9227";
      hash = "sha256-bj0QLHwYrZ1Qs2h8D5Wb94mU8k6t0UXypNmaLfT0MP8=";
      finalImageName = "floci-nix/aws-baseline";
      finalImageTag = "2.1.0-sha256-5e8d00757d225bdc";
      arch = "arm64";
    };
  };

  "azure" = {
    "x86_64-linux" = {
      version = "0.13.0";
      imageName = "floci/floci-az";
      upstreamTag = "0.13.0";
      imageDigest = "sha256:3a71953fbc0940aa33bbc1c5e88211a320b66812c0840831a9f8558d3d3521c5";
      hash = "sha256-fmMXvTaI7FyacJd+ZYRu1l4bv37MlatrFsMF+0V2Hxs=";
      finalImageName = "floci-nix/azure";
      finalImageTag = "0.13.0-sha256-3a71953fbc0940aa";
      arch = "amd64";
    };
    "aarch64-linux" = {
      version = "0.13.0";
      imageName = "floci/floci-az";
      upstreamTag = "0.13.0";
      imageDigest = "sha256:3a71953fbc0940aa33bbc1c5e88211a320b66812c0840831a9f8558d3d3521c5";
      hash = "sha256-kKK2NKhSsAYEeH0RLAzBKP8o0zK6ntnpTzGR3owJqP0=";
      finalImageName = "floci-nix/azure";
      finalImageTag = "0.13.0-sha256-3a71953fbc0940aa";
      arch = "arm64";
    };
  };

  "gcp" = {
    "x86_64-linux" = {
      version = "0.9.0";
      imageName = "floci/floci-gcp";
      upstreamTag = "0.9.0";
      imageDigest = "sha256:ea29a53b34d04ba05240cdc6833608e43ae2b0a67849e5b97f01a7224e1138ea";
      hash = "sha256-FjkWGM2MhccTOcx+aD/OYIP/k1PBTYRC2si/g4h28kM=";
      finalImageName = "floci-nix/gcp";
      finalImageTag = "0.9.0-sha256-ea29a53b34d04ba0";
      arch = "amd64";
    };
    "aarch64-linux" = {
      version = "0.9.0";
      imageName = "floci/floci-gcp";
      upstreamTag = "0.9.0";
      imageDigest = "sha256:ea29a53b34d04ba05240cdc6833608e43ae2b0a67849e5b97f01a7224e1138ea";
      hash = "sha256-aVbbjdS649ElDoVmAc3dhvRbpV8727JeiGN/Ml3uJb8=";
      finalImageName = "floci-nix/gcp";
      finalImageTag = "0.9.0-sha256-ea29a53b34d04ba0";
      arch = "arm64";
    };
  };

  "oci" = {
    "x86_64-linux" = {
      version = "0.4.1";
      imageName = "floci/floci-oci";
      upstreamTag = "0.4.1";
      imageDigest = "sha256:58b4b17069508b30e48bdf5888fd2759a52c23de082bd758484e3b8e2592b1cb";
      hash = "sha256-q2pX0i3xSseSK9tYK+n2y71dpkSFOe3PKPT09PRwL+c=";
      finalImageName = "floci-nix/oci";
      finalImageTag = "0.4.1-sha256-58b4b17069508b30";
      arch = "amd64";
    };
    "aarch64-linux" = {
      version = "0.4.1";
      imageName = "floci/floci-oci";
      upstreamTag = "0.4.1";
      imageDigest = "sha256:58b4b17069508b30e48bdf5888fd2759a52c23de082bd758484e3b8e2592b1cb";
      hash = "sha256-tfFDlYiC94zIPt7xuwzBY6ZZ9L2mutjPXk6CF9fzTZQ=";
      finalImageName = "floci-nix/oci";
      finalImageTag = "0.4.1-sha256-58b4b17069508b30";
      arch = "arm64";
    };
  };

  "oci-compat" = {
    "x86_64-linux" = {
      version = "0.4.1";
      imageName = "floci/floci-oci";
      upstreamTag = "0.4.1-compat";
      imageDigest = "sha256:68cf9caa29dea80b05330d61fc2222ed294acd165db93464ba250d0fe005aa04";
      hash = "sha256-LDkL49zWNcnvhxVOibGxc5l/HrcArR2gHTFljV1MUhY=";
      finalImageName = "floci-nix/oci-compat";
      finalImageTag = "0.4.1-sha256-68cf9caa29dea80b";
      arch = "amd64";
    };
    "aarch64-linux" = {
      version = "0.4.1";
      imageName = "floci/floci-oci";
      upstreamTag = "0.4.1-compat";
      imageDigest = "sha256:68cf9caa29dea80b05330d61fc2222ed294acd165db93464ba250d0fe005aa04";
      hash = "sha256-Yika6zEdzyTJHk2tm+OxYmuLL2f9PDrmNwfHwAEwTIQ=";
      finalImageName = "floci-nix/oci-compat";
      finalImageTag = "0.4.1-sha256-68cf9caa29dea80b";
      arch = "arm64";
    };
  };
}
